---
web:
  config:
    baseURL: http://flux.sand.pit.im
    authentication:
      type: OAuth2
      oauth2:
        provider: OIDC
        clientID: flux-web
        clientSecret: flux-web-secret
        issuerURL: http://dex.sand.pit.im
