---
# red-user: admin access scoped to the red namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-web-red-user
  namespace: red
  labels:
    sand.pit.im/addon: tenants
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-web-admin
subjects:
  - kind: User
    name: red-user@sand.pit.im
    apiGroup: rbac.authorization.k8s.io
---
# blue-user: admin access scoped to the blue namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-web-blue-user
  namespace: blue
  labels:
    sand.pit.im/addon: tenants
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-web-admin
subjects:
  - kind: User
    name: blue-user@sand.pit.im
    apiGroup: rbac.authorization.k8s.io
